### PR TITLE
Kotlin rewrite (IN-PROGRESS)

### PR DESCRIPTION
**Pull request by Doomsdayrs**
- Completely refactored to Kotlin
- Working on rewriting the data binding to be cleaner
- Replaced a lot of things with Kotlin standards

This is in progress, It is yet to be tested. And the data binding is 100% broken. 

Kotlin has numerous benefits over typical java. In my opinion its more efficient to code in Kotlin because there is a whole lot less to write for. Such as how you had a dozen 'search' functions. Now all replaced with 4

In gradle i had to comment out a few things, and i also bumped the gradle version to latest

### CODE REVIEW

**Comment by Kodehawa** [comment]
Thanks you for your time and the contributuion, but:

I was never asked about this, and as you can probably tell, this is a full rewrite of a program without telling me anything, on a different programming language which I'm way less familiar with.

You can keep a fork in Kotlin if you want, but I won't merge this into the main project as I'm gonna be the one maintaining it, and I'd rather have it on a language I actually know decently well.

Sorry, closing this one.

**Comment by Kodehawa** [comment]
Took a look at the code, since I was curious.

A few comments if you wanna keep your fork:

- Try to keep logback, it's way more useful than printf, specially for debugging! And you probably don't wanna throw everything under the user's console :)
- Tab indenting is broken on GH for whatever reason (it shows 8 spaces for every tab), that's why I used spaces.
- You might want to use Kotlin extensions more :)
- Why did you just remove e621 and e926? I don't like those imageboards myself, but people will use it, so it's worth keeping IMO.
- You could also just make kotlin extensions for this library instead of keeping a full fork afloat? There's been a good assortment of changes since this and keeping the fork up-to-date with that many changes might not be the easiest thing.

**Comment by Doomsdayrs** [comment]
- Tab indenting is alwaysss broken smhhh
- True
- I was having issues in getting them to work, i didn't know enough at the point to try to fix them
- Sure I could, But I used this to improve my kotlin skills, that I have implemented in my own projects. I often go around doing PRs like this one, as it further improves my skills with converting java to kotlin and structure kotlin more properly. In the half year from this project I have gotten eons better in writing my kotlin code.

**Comment by Kodehawa** [comment]
Fair enough.

Felt like a weird PR indeed. Could've said it was for learning purposes, so I could've helped you a little there by looking at it by then :)

> I was having issues in getting them to work, i didn't know enough at the point to try to fix them
They use weird as heck formats, no discussion there, lol.

> Tab indenting is alwaysss broken smhhh
Yup. Spaces work fine IMO, but if you prefer tabs that's fine :) I just use a plugin so my tabs on GH are 4 instead of 8, since dunno what the heck the people at GH were thinking when they made that 8.

> Sure I could, But I used this to improve my kotlin skills, that I have implemented in my own projects. I often go around doing PRs like this one, as it further improves my skills with converting java to kotlin and structure kotlin more properly. In the half year from this project I have gotten eons better in writing my kotlin code.

Worth a shot now then? :P

At least if you wanna do the extensions now. Dunno about your intentions. 
If you do it I'll put them on the readme though, since this code as-is is probably not the most Kotlin-friendly code out there :p  

Best of luck :)

**Pull request closed without merging**
