### PR TITLE
ImageBoard API 2.0

### PR DESCRIPTION
**Pull request by Avarel**
### Changelog
* Hella optimized af.
* Removed Utils.
* Removed the trash known as Lombok.
* Removed Gson.
* Renamed some classes.
* Reorganized classes.
* Moved several inner classes to their own files.
* Added `getScore()` to `BoardImage`.
* `Board.java` became common interface for board landing information.
  * Default board landings moved to `DefaultBoards.java`
  * `CustomBoard.java` allows for custom board landing information.
* `ImageBoardAPI.java` got a makeover, renamed to `ImageBoard.java`.
  * Previous `ImageBoards.java` renamed to `DefaultImageBoards.java`.
  * Now use request model, similar to that of JDA's.
  * Requester is now `RequestFactory`, returns `RequestAction<T>`.
  * No longer use array component classes for deserialization.
  * Moved mappers into an enum.
* Added `Ratings.java` enum.
* Added documentation everywhere.
* Added copyright notices everywhere.
* Cleaned up some tests.
* Cleaned up `README.md`

### CODE REVIEW

**Comment by Avarel** [comment]
Also note to self it’s nachtraben not napstr lol

**Comment by NachtRaben** [comment]
Wut I do?

**Comment by Kodehawa** [comment]
He put the wrong name on one of your classes lol

**Comment by Kodehawa** [comment]
closed on request

**Pull request merged**
